apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-web-app-deployment
  name: go-web-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-web-app-pods
  strategy: {}
  template:
    metadata:
      labels:
        app: go-web-app-pods
    spec:
      containers:
      - image: chockalingammuthukumar/go-web-app:latest
        name: go-web-app-containers
        ports:
          - containerPort: 8080
        resources: {}
status: {}
