apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-web-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: go-web-app.local
    http:
      paths:
      - backend:
          service:
            name: go-web-app-service
            port:
              number: 80
        path: /courses
        pathType: Exact
status:
  loadBalancer: {}
